---
-
  hosts: dev 
  user: ansible
  become: true
  tasks:
    - name: Set a fact
      set_fact:
        our_fact: Checking facts using Ansible !
        ansible_distribution: "{{ ansible_distribution | upper }}"

    - name: Show our_fact
      debug:
        msg: "{{ our_fact }}"

    - name: Show ansible_distribution
      debug:
        msg: "{{ ansible_distribution }}"
