---
-
  hosts: ut
  user: ansible
  become: true
  gather_facts: false
  serial: 
    - 1
    - 2
    - 3
  tasks:
    - name: Task 1
      command: /bin/sleep 5

    - name: Task 2
      command: /bin/sleep 5

    - name: Task 3
      command: /bin/sleep 5

    - name: Task 4
      command: /bin/sleep 5

    - name: Task 5
      command: /bin/sleep 5

    - name: Task 6
      command: /bin/sleep 5
