---
-
  hosts: ut
  user: ansible
  become: true
  tasks:
    - name: Creating user directories
      file:
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
      with_together:
        - [ raja, murali ]
        - [ japanese, coffee ]
